require 'azure'
require_relative 'kontena/machine/random_name'
require_relative 'azure/logger'
require_relative 'azure/node_provisioner'
require_relative 'azure/node_destroyer'
require_relative 'azure/master_provisioner'
