require 'azure'
require 'kontena/machine/random_name'
require 'kontena/machine/cert_helper'
require_relative 'azure/logger'
require_relative 'azure/node_provisioner'
require_relative 'azure/node_destroyer'
require_relative 'azure/master_provisioner'
